// AUTO-GENERATED by scripts/update-place-stats.mjs.
// Do not edit manually; the weekly GitHub Action refreshes these values.
export const GOOGLE_PLACE_STATS = {
  rating: 4.9,
  userRatingCount: 2494,
  updatedAt: "2026-09-27",
} as const;
