/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelLoginRouteImport } from './routes/painel/login'
import { Route as ApiDashboardSyncMetaAdsRouteImport } from './routes/api/dashboard/sync-meta-ads'
import { Route as ApiDashboardGetMetaDashboardRouteImport } from './routes/api/dashboard/get-meta-dashboard'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelLoginRoute = PainelLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PainelRouteRoute,
} as any)
const ApiDashboardSyncMetaAdsRoute = ApiDashboardSyncMetaAdsRouteImport.update({
  id: '/api/dashboard/sync-meta-ads',
  path: '/api/dashboard/sync-meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardGetMetaDashboardRoute =
  ApiDashboardGetMetaDashboardRouteImport.update({
    id: '/api/dashboard/get-meta-dashboard',
    path: '/api/dashboard/get-meta-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/obrigado': typeof ObrigadoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/': typeof PainelIndexRoute
  '/api/dashboard/get-meta-dashboard': typeof ApiDashboardGetMetaDashboardRoute
  '/api/dashboard/sync-meta-ads': typeof ApiDashboardSyncMetaAdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel': typeof PainelIndexRoute
  '/api/dashboard/get-meta-dashboard': typeof ApiDashboardGetMetaDashboardRoute
  '/api/dashboard/sync-meta-ads': typeof ApiDashboardSyncMetaAdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/obrigado': typeof ObrigadoRoute
  '/painel/login': typeof PainelLoginRoute
  '/painel/': typeof PainelIndexRoute
  '/api/dashboard/get-meta-dashboard': typeof ApiDashboardGetMetaDashboardRoute
  '/api/dashboard/sync-meta-ads': typeof ApiDashboardSyncMetaAdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/obrigado'
    | '/painel/login'
    | '/painel/'
    | '/api/dashboard/get-meta-dashboard'
    | '/api/dashboard/sync-meta-ads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obrigado'
    | '/painel/login'
    | '/painel'
    | '/api/dashboard/get-meta-dashboard'
    | '/api/dashboard/sync-meta-ads'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/obrigado'
    | '/painel/login'
    | '/painel/'
    | '/api/dashboard/get-meta-dashboard'
    | '/api/dashboard/sync-meta-ads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  ObrigadoRoute: typeof ObrigadoRoute
  ApiDashboardGetMetaDashboardRoute: typeof ApiDashboardGetMetaDashboardRoute
  ApiDashboardSyncMetaAdsRoute: typeof ApiDashboardSyncMetaAdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/login': {
      id: '/painel/login'
      path: '/login'
      fullPath: '/painel/login'
      preLoaderRoute: typeof PainelLoginRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/api/dashboard/sync-meta-ads': {
      id: '/api/dashboard/sync-meta-ads'
      path: '/api/dashboard/sync-meta-ads'
      fullPath: '/api/dashboard/sync-meta-ads'
      preLoaderRoute: typeof ApiDashboardSyncMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/get-meta-dashboard': {
      id: '/api/dashboard/get-meta-dashboard'
      path: '/api/dashboard/get-meta-dashboard'
      fullPath: '/api/dashboard/get-meta-dashboard'
      preLoaderRoute: typeof ApiDashboardGetMetaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteRouteChildren {
  PainelLoginRoute: typeof PainelLoginRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelLoginRoute: PainelLoginRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  ObrigadoRoute: ObrigadoRoute,
  ApiDashboardGetMetaDashboardRoute: ApiDashboardGetMetaDashboardRoute,
  ApiDashboardSyncMetaAdsRoute: ApiDashboardSyncMetaAdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
